@baseUrl = http://localhost:3001

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello/

### ExemploDeRota
# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### Concepts Home
# @name ConceptsHome
GET {{baseUrl}}/concepts/

### Conceitos Home
# @name ConceitosHome
GET {{baseUrl}}/conceitos/

### Messages
# @name MessageAll
GET {{baseUrl}}/messages/
?limit=10
&offset=10

### Message with params
# @name MessageParam
GET {{baseUrl}}/messages/3

### CreateMessage
# @name CreateMessage
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "Este é um recado de teste",
  "sender": "Joana",
  "receiver": "João"
}

### PatchMessage
# @name PatchMessage
PATCH  {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Atualizado"
}

### PutMessage
# @name PutMessage
PUT  {{baseUrl}}/messages/2
Content-Type: application/json

{
  "text": "Updated"
}

### DeleteMessage
# @name DeleteMessage
DELETE  {{baseUrl}}/messages/2
