@baseUrl = http://localhost:3001

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello/

### ExemploDeRota
# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### Concepts Home
# @name ConceptsHome
GET {{baseUrl}}/concepts/

### Conceitos Home
# @name ConceitosHome
GET {{baseUrl}}/conceitos/

### Messages
# @name MessageAll
GET {{baseUrl}}/messages/
# ?limit=10
# &offset=10

### Message with params
# @name MessageParam
GET {{baseUrl}}/messages/2

### CreateMessage
# @name CreateMessage
POST {{baseUrl}}/messages/
Content-Type: application/json

{
  "text": "recado",
  "sender": "Joana",
  "receiver": "João"
}

### PatchMessage
# @name PatchMessage
PATCH  {{baseUrl}}/messages/5
Content-Type: application/json

{
  "text": "Atualizado"
}

### PutMessage
# @name PutMessage
PUT  {{baseUrl}}/messages/5
Content-Type: application/json

{
  "text": "Updated",
  "sender": "João",
  "receiver": "Joana"
}

### DeleteMessage
# @name DeleteMessage
DELETE  {{baseUrl}}/messages/4

# People
### List all people
GET {{baseUrl}}/people/

### List person for id
GET {{baseUrl}}/people/3/

### Create person
POST {{baseUrl}}/people/
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "123456",
  "name": "Alan"
}

### PatchPerson
# @name PatchPerson
PATCH  {{baseUrl}}/people/12
Content-Type: application/json

{
  "password": "123456",
  "name": "Alan"
}

### PutPerson
# @name PutPerson
# PUT  {{baseUrl}}/people/12
# Content-Type: application/json

# {
#   "password": "Updated",
#   "name": "João"
# }

### DeletePerson
# @name DeletePerson
DELETE  {{baseUrl}}/people/11
